name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Decision Tree training and evaluation
      run: |
        python src/train_decision_tree.py

    - name: Run Kernel Ridge training and evaluation
      run: |
        python src/train_kernel_ridge.py

    - name: Run tests
      run: |
        pytest tests/