name: Kernel Ridge CI

on:
  push:
    branches:
      - kernelridge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run train.py
        run: |
          python src/train.py

      - name: Run train2.py
        run: |
          python src/train2.py