name: ML Workflow CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Decision Tree model
        run: python train_decision_tree.py

      - name: Run Kesrnel Ridge model
        run: python src/train_kernel_ridge.py